import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e7e0ed",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-secondary-container": "#00686f",
        "on-secondary": "#00363a",
        "on-primary": "#3c0091",
        "on-primary-container": "#340080",
        "on-primary-fixed-variant": "#5516be",
        "primary-container": "#a078ff",
        "surface-container-highest": "#37333d",
        "on-secondary-fixed-variant": "#004f54",
        "primary": "#d0bcff",
        "primary-fixed": "#e9ddff",
        "surface-container-high": "#2c2832",
        "on-secondary-fixed": "#002022",
        "outline-variant": "#494454",
        "on-tertiary-container": "#3f2300",
        "tertiary-container": "#ca801e",
        "tertiary-fixed": "#ffdcbb",
        "background": "#15121b",
        "surface-container-low": "#1d1a23",
        "on-error": "#690005",
        "surface-container": "#211e27",
        "on-primary-fixed": "#23005c",
        "inverse-primary": "#6d3bd7",
        "secondary-fixed-dim": "#00dbe9",
        "on-surface-variant": "#cbc3d7",
        "inverse-on-surface": "#322f39",
        "tertiary": "#ffb869",
        "secondary": "#d3fbff",
        "on-tertiary-fixed-variant": "#673d00",
        "on-error-container": "#ffdad6",
        "on-surface": "#e7e0ed",
        "secondary-fixed": "#7df4ff",
        "tertiary-fixed-dim": "#ffb869",
        "surface-tint": "#d0bcff",
        "primary-fixed-dim": "#d0bcff",
        "secondary-container": "#00eefc",
        "outline": "#958ea0",
        "on-background": "#e7e0ed",
        "surface-container-lowest": "#0f0d15",
        "surface-variant": "#37333d",
        "on-tertiary-fixed": "#2c1700",
        "surface-bright": "#3b3742",
        "on-tertiary": "#482900",
        "surface-dim": "#15121b",
        "surface": "#15121b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "container-max": "1200px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "unit": "4px",
      },
      fontFamily: {
        "headline-md": ["Space Mono"],
        "headline-lg": ["Space Mono"],
        "body-standard": ["Outfit"],
        "body-dialogue": ["Courier Prime"],
        "label-pixel": ["Space Mono"],
        "headline-lg-mobile": ["Space Mono"],
        "press-start": ['"Press Start 2P"', "cursive"],
        "vt323": ['"VT323"', "monospace"],
      },
      fontSize: {
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.05em", fontWeight: "700" }],
        "body-standard": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-dialogue": ["18px", { lineHeight: "24px", fontWeight: "400" }],
        "label-pixel": ["10px", { lineHeight: "12px", fontWeight: "700" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
